[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install", "cd client && npm install"]

[phases.build] 
cmds = ["npm run build", "cd client && npm run build"]

[start]
cmd = "npm run start:prod"