# Nixpacks configuration for Railway deployment
[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
    "npm ci --omit=dev",
    "cd client && npm ci --omit=dev"
]

[phases.build] 
cmds = [
    "npm install",
    "npm run build",
    "cd client && npm install && npm run build"
]

[start]
cmd = "NODE_ENV=production node dist/index.js"